# Generated by Django 3.2.6 on 2021-08-24 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='perfil',
            field=models.ImageField(max_length=200, upload_to='static/img/', verbose_name='imagen de perfil'),
        ),
    ]
